spring:
  application:
    name: ecommerce

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e_commerce?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.uoa.ecommerce.entity

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.uoa.ecommerce.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
